### ISSUE TITLE
newuidmap requires CAP_SYS_ADMIN (rather than CAP_SET{U,G}ID)?

### ISSUE THREAD

**Issue by AkihiroSuda** [genuinetools/img#170]
```yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: img
  name: img
  annotations:
    container.apparmor.security.beta.kubernetes.io/img: unconfined
spec:
  securityContext:
    runAsUser: 1000
  initContainers:
    # This container clones the desired git repo to the EmptyDir volume.
    - name: git-clone
      image: r.j3ss.co/jq
      args:
        - git
        - clone
        - --single-branch
        - --
        - https://github.com/jessfraz/dockerfiles
        - /repo # Put it in the volume
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
      volumeMounts:
        - name: git-repo
          mountPath: /repo
  containers:
  - image: r.j3ss.co/img
    imagePullPolicy: Always
    name: img
    resources: {}
    workingDir: /repo
    command:
    - img
    - build
    - -t
    - irssi
    - irssi/
    securityContext:
      procMount: Unmasked
      capabilities:
        add:
        - SYS_ADMIN
    volumeMounts:
    - name: cache-volume
      mountPath: /tmp
    - name: git-repo
      mountPath: /repo
  volumes:
  - name: cache-volume
    emptyDir: {}
  - name: git-repo
    emptyDir: {}
  restartPolicy: Never
```

The YAML above (based on https://blog.jessfraz.com/post/building-container-images-securely-on-kubernetes/) works with Kubernetes 1.12.1 + Docker 18.06.1 (Minikube PR: https://github.com/kubernetes/minikube/pull/3223).

However, when I `add` `SETUID` and `SETGID` to `capabilities` instead of `SYS_ADMIN`, `newuidmap` fails:
(EDIT: `SETUID` and `SETGID` are already in the default set, and adding them explicltly is just "NOP")
```
newuidmap: write to uid_map failed: Operation not permitted
nsenter: failed to use newuidmap: Invalid argument
nsenter: failed to sync with parent: SYNC_USERMAP_ACK: got 255: Invalid argument
```

cc @jessfraz @cyphar @giuseppe
