### ISSUE TITLE
nsenter: failed to unshare namespaces: Invalid argument

### ISSUE THREAD

**Issue by DanOpi** [genuinetools/img#240]
I have seen other issues surrounding this but it sounded like a Mac problem originally so hoping to give a bit more info and see if there's a solution.

Kubernetes Server Version: `v1.12.4`
Container Runtime Version:  `docker 18.6.3`

I cloned `master` and ran a `docker build` and `docker push` to my registry and then created a Pod spec with an initContainer to clone a repo to a volumeMount and then added the `img` container that referenced the cloned repo on the same volumeMount.

I am unable to set `procMount: Unmasked` because `Unamsked` is not allowed on the cluster at this time but I saw @AkihiroSuda mention this shouldn't be needed anymore.

The `img` container fails with the following error:

    nsenter: failed to unshare namespaces: Invalid argument

Any ideas or input on how to work around/solve this issue?

Example Yaml:

```
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: img
    app: git-clone
  name: img
  annotations:
    container.apparmor.security.beta.kubernetes.io/img: unconfined
spec:
  securityContext:
    runAsUser: 1000
  initContainers:
    - name: git-clone
      image: docker.myregistry.com/git
      command:
        - git
        - clone
        - https://mygithub.com/myorg/myrepo.git
        - /workspace
      volumeMounts:
        - name: source
          mountPath: /workspace
  containers:
    - image: docker.myregistry.com/img
      imagePullPolicy: Always
      name: img
      resources: {}
      workingDir: /workspace
      command:
        - img
        - build
        - -t
        - testimage
        - "."
      volumeMounts:
        - name: cache-volume
          mountPath: /tmp
        - name: source
          mountPath: /workspace
  volumes:
    - name: cache-volume
      emptyDir: {}
    - name: source
      emptyDir: {}
  restartPolicy: Never
```
