### ISSUE TITLE
nsenter: failed to unshare namespaces: Invalid argument  script returned exit code 20

### ISSUE THREAD

**Issue by marshallford** [genuinetools/img#247]
I was excited to see this sentence in the README and figured I give it ago having not tried the last couple of releases:

> Since img v0.5.7, you don't need to specify any securityContext for running img as a Kubernetes container.

Pod:
```
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: jnlp
    image: jenkins/jnlp-slave:3.29-1-alpine
  - name: img
    image: jess/img:v0.5.7
    command:
    - cat
    tty: true
```
Dockerfile used to test:
```
➜ cat Dockerfile
FROM alpine
RUN date
```

Output:
```
img build -t foo:latest .
nsenter: failed to unshare namespaces: Invalid argument
script returned exit code 20
```
