### ISSUE TITLE
failed to solve: failed to read dockerfile

### ISSUE THREAD

**Issue by sjames** [genuinetools/img#260]
Hi,
I have built img from source and am trying to run the examples. I'm doing this on an Ubuntu 18.04 machine.

`sjames@sjames-ideapad:~/playground/img$ img build -t r.j3ss.co/img .
Building r.j3ss.co/img:latest
Setting up the rootfs... this may take a bit.

[+] Building 1.2s (2/2) FINISHED                                                
 => [internal] load build definition from Dockerfile                       0.8s
 => => transferring dockerfile: 2B                                         0.0s
 => [internal] load .dockerignore                                          1.1s
 => => transferring context: 47B                                           0.1s

Error: failed to solve: failed to read dockerfile: open /tmp/buildkit-mount368416638/Dockerfile: no such file or directory
sjames@sjames-ideapad:~/playground/img$ uname -a
Linux sjames-ideapad 5.0.0-23-generic #24~18.04.1-Ubuntu SMP Mon Jul 29 16:12:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
`

**Comment by daviddyball** [comment]
I'm also getting this when I use `img` as a container in a Kubernetes Pod spawned by the Jenkins Kubernetes plugin. The Kubernetes Jenkins plugin mounts the working directory into each container in the pod and I'm wondering if this is something to do with the `Dockerfile` living on a mounted volume?

My Pod YAML:
```
apiVersion: v1
kind: Pod
metadata:
  generate-name: agent-k8s-
  labels:
    name: jnlp
    label: jnlp
spec:
  securityContext:
    runAsUser: 0
    privileged: true
  containers:
  - name: img
    image: r.j3ss.co/img:v0.5.7
    imagePullPolicy: Always
    command:
    - cat
    tty: true
  - name: git
    image: alpine/git:1.0.4
    command:
    - cat
    tty: true
  - name: charttester
    image: charttester:1.0.0
    command:
    - cat
    tty: true
```
