### ISSUE TITLE
img push --insecure-registry does not seem to work

### ISSUE THREAD

**Issue by Kelvin-M** [genuinetools/img#297]
Hello,
I'm running into an issue by trying to push an image to a local registry on kubernetes

### Steps to reproduce the behavior
Here what I'm doing : 

1. Setup local registry
``` bash 
helm install -n registry stable/docker-registry
```

2. Create a local pod with img docker image, which reproduce a push with `insecure-registry` option
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: img-test
spec:
  containers:
  - name: img-test
    image: r.j3ss.co/img:v0.5.9
    command: ["/bin/sh", "-c"]
    args: ["img pull busybox:1.31.1; img tag busybox:1.31.1 registry-docker-registry:5000/busybox:1.31.1; img push --insecure-registry=true registry-docker-registry:5000/busybox:1.31.1"]
  restartPolicy: Never
```

You can also do 
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: img-test
spec:
  containers:
  - name: img-test
    image: r.j3ss.co/img:v0.5.9
    command: ["/bin/sh", "-c"]
    args: ["sleep 3600"]
  restartPolicy: Never
```

And launch the command manually : 
```bash
kubectl exec img-test -- img pull busybox:1.31.1
kubectl exec img-test -- img tag busybox:1.31.1 registry-docker-registry:5000/busybox:1.31.1
kubectl exec img-test -- img push --insecure-registry=true registry-docker-registry:5000/busybox:1.31.1
```

Results : 
```
Pushing registry-docker-registry:5000/busybox:1.31.1...
Error: failed to do request: Head https://registry-docker-registry:5000/v2/busybox/blobs/sha256:759344404bffa09286afe8f43530d0e6e0f59ff025ea9d671e899ceb06666537: http: server gave HTTP response to HTTPS client
```

The registry is accessible

```bash
kubectl exec img-test  -- wget -q -O- registry-docker-registry:5000/v2/_catalog
```

I tried with 
```
 --insecure-registry=true #  but also with TRUE, True, 1
 --insecure-registry true #  does not work because it is not taken into account, true is considered as the image to push ^^
 --insecure-registry # blank
```
### Questions:
 - Am I missing something in my example that prevent it from working ?
 - Is the insecure-registry option is not working at all ?

Thank you for your help !
